name: Build plugin.zip
on:
    release:
        types:
            - created
jobs:
    BuildAndUploadZip:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            -   name: checkout
                uses: actions/checkout@v4
                with:
                    path: repo
            -   name: git archive
                run: cd repo && git archive --format=zip -o ../plugin.zip ${{github.ref}}
            -   name: upload
                run: gh release upload ${{github.ref_name}} plugin.zip --repo ${{github.repository}}
