name: Build plugin.zip
on:
    release:
        types:
            - created
jobs:
    BuildAndUploadZip:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            -   name: checkout
                uses: actions/checkout@v4
                with:
                    path: repo
            -   name: build zip tree
                run: |
                    set -e
                    mkdir zip
                    cp -r repo/lr-pristine-raw-importer.lrplugin zip/
                    cp repo/LICENSE zip/lr-pristine-raw-importer.lrplugin/
                    sed -i 's|%%GITHUB_REF_NAME%%|${{github.ref_name}}|g' zip/lr-pristine-raw-importer.lrplugin/Settings.lua
                    sed -i 's|%%GITHUB_SHA%%|${{github.sha}}|g' zip/lr-pristine-raw-importer.lrplugin/Settings.lua
            -   name: build zip file
                run: env -C zip zip -r "$PWD/plugin.zip" .
            -   name: upload
                run: gh release upload ${{github.ref_name}} plugin.zip --repo ${{github.repository}}
